name: Log check run events

on: check_run

jobs:
  log-check-run:
    name: Log all check run events
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "$EVENT"
        env:
          EVENT: ${{ toJson(github.event) }}
