name: Log check suite events

on: check_suite

jobs:
  log-check-suite:
    name: Log all check suite events
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "$EVENT"
        env:
          EVENT: ${{ toJson(github.event) }}
